# Generated by Django 5.1 on 2024-08-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_inicial', models.DateField()),
                ('data_encerramento', models.DateField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
